name: changelog-manager
description: 'Manage changelog file'
inputs:
  path:
    description: 'Path to the changelog file'
    required: false
    default: 'CHANGELOG.md'
  format:
    description: 'Format of the changelog file'
    required: false
    default: 'markdownlint'
  encoding:
    description: 'Encoding of the changelog file'
    required: false
    default: 'UTF-8'
  action:
    description: 'Action to perform'
    required: false
    default: 'auto'
  release_version:
    description: 'Release version'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'src/github-action.js'
