name: changelog-manager
description: 'Manage changelog file'
inputs:
  file:
    description: 'Changelog file path'
    default: 'CHANGELOG.md'
    required: false
  format:
    description: 'Format of the changelog file (markdownlint or compact)'
    default: 'markdownlint'
    required: false
  encoding:
    description: 'Encoding of the changelog file'
    default: 'UTF-8'
    required: false
  action:
    description: 'Action to perform'
    default: 'fmt'
    required: false
  fmt_write:
    description: '(action=fmt) Write formatted changelog back to file'
    default: false
    required: false
  release_version:
    description: '(action=release) Release version'
    default: ''
    required: false
  commit:
    description: 'Commit and push changes into the repository'
    default: 'true'
    required: false
  commit_message:
    description: 'Commit message'
    default: 'Update changelog'
    required: false
  commit_username:
    description: 'Commit username'
    default: 'github-actions[bot]'
    required: false
  commit_user_email:
    description: 'Commit user email'
    default: '41898282+github-actions[bot]@users.noreply.github.com'
    required: false
runs:
  using: 'node20'
  main: 'src/github-action.js'
