on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  manage_changelog:
    runs-on: ubuntu-latest
    name: Manage changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Manage changelog
        uses: TheoBrigitte/test@e79a58abc420f6cc81403eaf75367aac754a1355
