on: [push]

jobs:
  validate_changelog:
    runs-on: ubuntu-latest
    name: Validate Changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate Changelog
        uses: TheoBrigitte/test@56acf254e43365053967354c315e673d9a979415
