on: [push]

jobs:
  validate_changelog:
    runs-on: ubuntu-latest
    name: Validate Changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate Changelog
        uses: TheoBrigitte/test@b6c00fc32f219db9d7b55869359669e20a50f5e6
