on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  manage_changelog:
    runs-on: ubuntu-latest
    name: Manage changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Manage changelog
        uses: TheoBrigitte/test@e93e5a4ecc74bc30990077d7ebee7f711bcfe62e
