on: push
#push:
#pull_request:
#  types: [opened, reopened]

jobs:
  manage_changelog:
    runs-on: ubuntu-latest
    name: Manage changelog
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Manage changelog
        uses: TheoBrigitte/test@f6b80a5e49fdba0a9e5b0a3e85b25ede539ff4e8
        with:
          fmt_write: true
      - uses: stefanzweifel/git-auto-commit-action@v5
