on: [push, pull_request]

jobs:
  validate_changelog:
    runs-on: ubuntu-latest
    name: Validate Changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate Changelog
        uses: TheoBrigitte/test@578ee060302face49690998bc2f5cad8c2e5b59b
