on: push
#push:
#pull_request:
#  types: [opened, reopened]

jobs:
  manage_changelog:
    runs-on: ubuntu-latest
    name: Manage changelog
    steps:
      - name: Checkout code
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        uses: actions/checkout@v4
      - name: Manage changelog
        uses: TheoBrigitte/test@c6e509e7f5d2dad08328e7994f369a00b5b7169d
