on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  manage_changelog:
    runs-on: ubuntu-latest
    name: Manage changelog
    steps:
      - name: Checkout code
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        uses: actions/checkout@v4
      - name: Manage changelog
        uses: TheoBrigitte/test@817d83af2917d0144ab1a967c77a9ff6aeccaeb3
